// ===== НАВИГАЦИЯ =====
document.addEventListener('DOMContentLoaded',function(){const b=document.getElementById('burgerMenu'),m=document.querySelector('.nav-menu');if(b&&m){b.addEventListener('click',function(){this.classList.toggle('active');m.classList.toggle('active')})}document.querySelectorAll('.nav-menu a').forEach(l=>{l.addEventListener('click',()=>{if(m)m.classList.remove('active');if(b)b.classList.remove('active')})})});

// ===== МОДАЛЬНОЕ ОКНО ПОМОЩИ =====
document.addEventListener('DOMContentLoaded',function(){const b=document.getElementById('helpBtn'),m=document.getElementById('helpModal'),c=document.getElementById('helpClose');if(!b||!m)return;function o(m){m.classList.add('active');document.body.style.overflow='hidden'}function l(m){m.classList.remove('active');document.body.style.overflow=''}b.addEventListener('click',e=>{e.preventDefault();o(m)});if(c)c.addEventListener('click',()=>l(m));m.addEventListener('click',e=>{if(e.target===m)l(m)})});

// ===== УПРАВЛЕНИЕ IP-АДРЕСОМ =====
document.addEventListener('DOMContentLoaded',function(){const h=document.getElementById('ip-hidden'),v=document.getElementById('ip-visible'),c=document.getElementById('copyBtn');if(!h||!v)return;let r=false,t=null;function copy(){if(!r)reveal();navigator.clipboard.writeText('play.surgoodcraft.ru').then(()=>{if(c){c.textContent='✅ Скопировано!';c.classList.add('copied');setTimeout(()=>{if(r&&c){c.textContent='📋 Копировать';c.classList.remove('copied')}},2000)}}).catch(()=>alert('Не удалось скопировать IP. Попробуйте вручную.'))}function reveal(){if(t)clearTimeout(t);h.style.display='none';v.style.display='inline-block';r=true;t=setTimeout(hide,5000)}function hide(){h.style.display='inline-block';v.style.display='none';r=false;if(c){c.textContent='📋 Копировать';c.classList.remove('copied')}if(t){clearTimeout(t);t=null}}h.addEventListener('click',e=>{e.stopPropagation();if(!r)reveal()});if(c)c.addEventListener('click',e=>{e.stopPropagation();copy()});document.addEventListener('click',e=>{const d=document.querySelector('.detail-item');if(d&&!d.contains(e.target)&&r)hide()})});

// ===== ЭФФЕКТ ПРИ ЗАГРУЗКЕ =====
window.addEventListener('load',function(){const b=document.querySelector('.center-block');if(b){b.style.animation='none';b.offsetHeight;b.style.animation='fadeInUp 0.8s ease'}});

// ===== ПОИСК ПО МОДАМ =====
document.addEventListener('DOMContentLoaded',function(){const s=document.getElementById('modSearch'),c=document.querySelectorAll('.mod-card'),m=document.getElementById('modCount');if(!s)return;function u(){const v=document.querySelectorAll('.mod-card:not(.hidden)').length;if(m)m.textContent=v}s.addEventListener('input',function(){const q=this.value.toLowerCase().trim();c.forEach(c=>{const n=(c.dataset.name||'').toLowerCase(),d=(c.dataset.desc||'').toLowerCase();c.classList.toggle('hidden',!(n.includes(q)||d.includes(q)))});u()});u()});